### ISSUE TITLE
Feature Request: Option to Disable Cookies additionally by name

### ISSUE THREAD

**Issue by mbruess1** [danielnegoita/vue-cookie-toggler#1]
First of all: Thanks for sharing such a fantastic cookie toggler! I was looking all over the place for a cookie consent tool that allows more than just consenting to everything. And yours does exactly that. 
But I was also looking for just one more functionality – thus, this feature request. 
I would love to see an option to disable cookies not only by categories but also by name implemented. E.g. If you have "Google Analytics" and "Google Optimize"under the category "analytics", you would be able to choose to allow "Google Analytics" but not "Google Optimize".

**Comment by danielnegoita** [comment]
I know about this 'need' and I am considering adding this feature, however not too soon. My time is limited now, and I already have a list of things to do planned for the next releases.

**Comment by mbruess1** [comment]
Okay, sure. That is understandable. But nice to here, that you are considering adding this feature. I am already looking forward to the next releases.
